LCAS/topological_navigation

topological_navigation/CMakeLists.txt, topological_navigation/src/topological_navigation/manager.py
Additions:
- yaw and xy goal tolerances are no longer hardcoded in `add_topological_node` and so the defaults can be modified more easily
- vertices for the influence zone are generated by a function rather than hardcoded
- distance for determining close nodes is an optional parameter to `add_topological_node`
=> Minor quality of life improvements for map_manager

topological_navigation/scripts/execute_policy_server.py, topological_navigation/scripts/navigation.py
`max_trans_vel` is replaced by `max_vel_trans` in melodic. As of now, this parameter is reconfigured after each edge in `execute_policy_server.py`, but not in `navigate.py`. 
To make this backward compatible with `kinetic`, both `max_trans_vel` and `max_vel_trans` are configured for setting. However, as reconfiguration for all configured parameters are done in a single step, using `try... except...` might be difficult. As a temp fix, only the existing parameters will be tried to be reconfigured now. 
This may fix #10
=> max_vel_trans fix for melodic

topological_navigation/launch/topo_nav_global.launch, topological_navigation/launch/topo_nav_local.launch, topological_navigation/scripts/go_to_node.py, topological_navigation/scripts/navigation.py
Fixes #11
Note that the remap in topo_nav_local assumes that the topological map is always published in the / namespace, which may not be correct.
=> Fix go_to_node not being available with namespaced topological_navigation

topological_navigation/scripts/navigation.py
Navigation.py was checking the existence of move base params without providing the namespace.
=> Fixed issue that broke dynamic reconfigure of move base params.

topological_navigation/scripts/localisation.py, topological_navigation/src/topological_navigation/manager.py, topological_navigation/src/topological_navigation/manager2.py, topological_navigation/src/topological_navigation/tmap_utils.py
This includes its services.
To localise using the new map type pass the arg `-use_tmap2` i.e. `rosrun topological_navigation localisation.py -use_tmap2`
Robot localises in the topological map using the topological map to baselink tf transform.
When an old map is loaded in the map manager, it is automatically converted to the new type and the default identity transform between the topomap and the map is broadcast.
=> All functions in localisation now work with the new map type.

topological_utils/CMakeLists.txt
The release version of the package is missing some of the scripts, insert_empty_map is particularly useful.
=> add missing scripts to cmakelists

topological_navigation/CMakeLists.txt, topological_navigation/scripts/TopologicalTransformPublisher.py, topological_navigation/scripts/localisation.py, topological_navigation/scripts/topological_transform_publisher.py
It is set by a rosparam `topological_localisation/base_frame` (default=`base_link`).
topomap frame is retrieved from the topological map.
Includes a new node `topological_transform_publisher` for publishing the map to topomap transform on the topic `/topological_transform` with msg type `geometry_msgs/TransformStamped`
removed unused imports from localisation.
=> Base frame used by localisation is no longer hard coded (in toponav 2).

topological_navigation/src/topological_navigation/manager2.py, topological_navigation_msgs/CMakeLists.txt, topological_navigation_msgs/srv/UpdateRestrictions.srv
Restrictions field for a node or an edge is now a string which is a boolean sentence (default="True").
New services `/topological_map_manager2/update_node_restrictions` and `/topological_map_manager2/update_edge_restrictions` added in the map manager 2.
=> Map manager services for updating restrictions

topological_navigation/src/topological_navigation/manager2.py, topological_navigation_msgs/srv/UpdateRestrictions.srv
Both are boolean sentences (default="True")
Update restrictions services modified to account for this.
If updating node restrictions then apply planning restrictions to edges involving the node.
Set this behaviour with new boolean arg `update_edges` in srv for updating a node's restrictions
=> Nodes and edges have two restrictions fields, one for planning restrictions and one for runtime restrictions.

topological_navigation/src/topological_navigation/edge_reconfigure_manager.py
The manager only resets params that have been reconfigured (not the whole configuration for a namespace).
More efficient.
=> Edge Reconfigure Improvements

topological_navigation/CMakeLists.txt, topological_navigation/package.xml, topological_navigation/scripts/navigation.py, topological_navigation/src/topological_navigation/edge_action_manager.py, topological_navigation/src/topological_navigation/edge_reconfigure_manager.py, topological_navigation/src/topological_navigation/manager2.py, topological_navigation/src/topological_navigation/route_search2.py, topological_navigation/src/topological_navigation/tmap_utils.py, topological_navigation_msgs/CMakeLists.txt, topological_navigation_msgs/srv/UpdateActionType.srv
Resolves https://github.com/LCAS/topological_navigation/issues/36
The args in the edge's goal field map directly to the args of the ROS msg specified in the edge's action type field.
Properties of the edge's destination node can be passed to the goal.
Therefore actions that can be executed by toponav are no longer limited to those that use move base type goals.
An 'EdgeActionManager' class has been made to handle most of this (generation of the goal, action client and the execution of the action).
Monitored navigation removed.
New manager 2 srv for updating the action type of each edge in the tmap according to the action name.
get_node_from_tmap2 utility modified so it returns all of the node inc its meta info and consequent changes to other files.
Functions of edge reconf manager called …
=> Topological navigation can handle any type of goal.

topological_navigation/config/sample_edge_reconfig_groups.yaml, topological_navigation/scripts/navigation.py, topological_navigation/src/topological_navigation/manager2.py, topological_navigation_msgs/CMakeLists.txt, topological_navigation_msgs/srv/UpdateAction.srv, topological_navigation_msgs/srv/UpdateActionType.srv
Map manager service for setting the action, action type and goal for an edge
Map manager service for setting the action type and goal for any edge with a given action
Retained ability to do edge reconfigure in the old way via param `/topological_navigation/reconfigure_edges_srv` (default=True). Example config provided.
=> Map manager services for updating edge action, type and goal. 

topological_navigation/config/sample_edge_reconfig_groups.yaml, topological_navigation/scripts/localisation.py, topological_navigation/scripts/map_manager2.py, topological_navigation/scripts/navigation.py, topological_navigation/src/topological_navigation/edge_action_manager.py, topological_navigation/src/topological_navigation/edge_reconfigure_manager.py, topological_navigation/src/topological_navigation/manager.py, topological_navigation/src/topological_navigation/manager2.py
Map manager switch maps service converts from tmap1 to tmap2 and map manager 2 switch maps service converts from tmap2 to tmap1.
Pass the filename (without the path) to the service request.
Map manager cwd set by param `/topological_map_path` if using the old manager and `/topological_map2_path` if using the new map manager.
Get filename from params `/topological_map_filename` and `/topological_map2_filename`.
Fix for switch map srv responding with error when converting from tmap1 to tmap2.
Lots of small improvements and tidying.
=> Switch map srv looks for maps in current working directory and also converts from tmap1 to tmap2 and vice-versa.

topological_navigation/scripts/navigation.py
Set with param `max_dist_to_closest_edge` (default = 1 meter)
Robot will NOT attempt to navigate from the closest edge if EITHER of the following are true:
a) the distance to closest edge > `max_dist_to_closest_edge`
b) current node != "none"
Else the robot will navigate from the closest node in exactly the same way as it has always done.
=> Navigating from the closest edge is now optional.

topological_navigation/src/topological_navigation/manager2.py, topological_navigation_msgs/CMakeLists.txt, topological_navigation_msgs/srv/UpdateEdge.srv, topological_navigation_msgs/srv/UpdateFailPolicy.srv
- Service `/topological_map_manager2/update_edge` now has field for updating the edge's fail policy.
- New service `/topological_map_manager2/update_fail_policy` for updating the fail policy of every edge in the map.
=> Services for updating the fail policy.

topological_navigation/scripts/navigation.py, topological_navigation/src/topological_navigation/route_search2.py
Implements the following fail policy actions:
- **retry_N** with N the number of retries, tries again to execute the same action;
- **wait_S_N** with S the number of seconds and N the number of waits, wait action;
- **replan**, generates a new plan which does not pass through the same edge where the fail occurred;
- **fail**, fails the entire plan.
=> working version of a "quick&dirty" implementation of the fail_policy

topological_navigation/scripts/navigation.py, topological_navigation/src/topological_navigation/manager2.py, topological_navigation_msgs/srv/UpdateFailPolicy.srv, topological_utils/scripts/edge_reconf_groups_to_tmap2.py
- Set `advertise_srvs` arg to False when initialising the map manager 2 allows other scripts/nodes to use its functions without advertising 20+ services.
- Descriptions of fail policy actions added to `UpdateFailPolicy.srv`.
- Tidying.
=> A few final things.

topological_navigation/scripts/navigation.py
Resolves https://github.com/LCAS/topological_navigation/issues/120
You will need to set the param `move_base_planner` to an action that is being used e.g. `row_traversal`
Merge with https://github.com/SAGARobotics/SagaApps/pull/427 and https://github.com/LCAS/RASberry/pull/1181
=> Fixes toponav breaking when move base is not being used

topological_navigation/src/topological_navigation/manager2.py, topological_navigation_msgs/msg/AddEdgeReq.msg, topological_navigation_msgs/srv/AddEdge.srv, topological_utils/CMakeLists.txt, topological_utils/config/goal.yaml, topological_utils/scripts/goal_converter.py
If a file e.g. `package/config/Goal.yaml` exists then the map manager will automatically set the goal of the action to the goal specified in that file, when the add edge function/service is called with arg `action_type` set to package/Goal. If that arg is not set or the file does not exist then a move base type goal is assumed.
=> Auto set goal when adding an edge to the topological map

topological_navigation/config/move_base_goal.yaml, topological_navigation/config/navigation_goal.yaml, topological_navigation/package.xml, topological_navigation/setup.py, topological_navigation/test/conf/network_autogen.tmap2.yaml, topological_navigation/test/static_transformer.py, topological_navigation/test/test_navigationcore.py, topological_navigation/tests/conf/test.tmap2, topological_navigation/topological_navigation/edge_action_manager2.py, topological_navigation/topological_navigation/edge_reconfigure_manager2.py, topological_navigation/topological_navigation/manager2.py, topological_navigation/topological_navigation/route_search2.py, topological_navigation/topological_navigation/scripts/localisation2.py, topological_navigation/topological_navigation/scripts/navigation.py, topological_navigation/topological_navigation/scripts/navigation2.py, topological_navigation/topological_navigation/scripts/param_processing.py, topological_navigation_msgs/CMakeLists.txt, topological_navigation_msgs/action/ExecutePolicyMode.action, topological_navigation_msgs/msg/ExecutePolicyModeFeedback.msg, topological_navigation_msgs/msg/GotoNodeFeedback.msg
- Topological Navigation (Core)
- Topological Navigation (ExecutePolicyMode Action Server)
- Topological Navigation (GoToNode Action Server)
- Topological Localisation (Core)
To validate 
ros2 action send_goal /topological_navigation topological_navigation_msgs/action/GotoNode "{target: WayPoint140}" 
ros2 action send_goal /topological_navigation/execute_policy_mode 
topological_navigation_msgs/action/ExecutePolicyMode `"{route: {source: [WayPoint140,WayPoint74], edge_id: 
[WayPoint140_WayPoint74, WayPoint74_r4.5-ca]}}"
=> Adding the following core functionalities 
