topological_navigation/scripts/execute_policy_server.py
topological_navigation/scripts/navigation.py

Teb can be reconfigured by toponav

---

topological_navigation/src/topological_navigation/manager.py

Services modified to work when loading topological maps from tmap files:
- `/topological_map_manager/get_tags`
- `/topological_map_manager/get_node_tags`
- `/topological_map_manager/add_tag_to_node`
- `/topological_map_manager/get_tagged_nodes`

Making map manager srvs work when loading map from tmap files.

---

topological_navigation/scripts/execute_policy_server.py
topological_navigation/scripts/navigation.py

Adds a key to the dynparam mappings to allow dynamic reconfiguration.

Allow use of EBandPlannerROS as local planner

---

topological_navigation/src/topological_navigation/manager.py

When using the service the `req.pointset` is the file path + name.

switch topological maps srv works when loading tmaps from files

---

topological_navigation/README.md
topological_navigation/scripts/localisation.py
topological_navigation/src/topological_navigation/point2line.py

Vectorised the toponav version of point2line, such that localisation can pass it a numpy array of edges (an array of vectors) and get it to return the distances to every edge in the map at once.

Efficient computing of closest edges in localisation.

---

topological_navigation/scripts/navigation.py
topological_navigation/src/topological_navigation/route_search2.py

Is now faster than the route planner for legacy toponav.
Approx 7 % faster on the riseholme transportation map.
Approx 37 % faster on the clockhouse vanity transportation map.

Faster Route Planner for Toponav 2

---

topological_navigation/src/topological_navigation/route_search2.py

Is now 15 % faster than legacy version for riseholme transportation map (previous improvement was 7%)
Is now 60 % faster than legacy version for clockhouse vanity transportation map (previous improvement was 37%)

Faster route planner.

---

topological_navigation/launch/topological_navigation.launch
topological_navigation/launch/topological_restrictions_multirobot.launch
topological_navigation/scripts/navigation.py
topological_navigation/src/topological_navigation/manager.py
topological_navigation/src/topological_navigation/manager2.py

Option to use restricted map in main toponav launch file.
Extension for new map is `.tmap2`

Navigation defaults to using edge reconfigure.

---

topological_navigation/scripts/navigation.py

Resolves https://github.com/LCAS/topological_navigation/issues/129

Edge reconfigure when target and origin nodes are the same

---

topological_navigation/scripts/navigation.py
topological_navigation/src/topological_navigation/edge_action_manager.py

Load tmap2s with json to decrease RAM usage

---

topological_navigation/src/topological_navigation/manager2.py

Map manager uses multiprocessing to load topomaps to decrease RAM usage.

---

topological_navigation/scripts/localisation.py
topological_navigation/scripts/navigation.py
topological_navigation/src/topological_navigation/manager2.py

Prevents toponav breaking when sending a goal before it is initialised.

Create action servers at end of initialisation.

---

topological_navigation/CMakeLists.txt
topological_navigation/launch/minimal_topological_navigation.launch
topological_navigation/launch/topological_navigation.launch
topological_navigation/package.xml
topological_navigation/scripts/visualise_map2.py
topological_navigation/src/topological_navigation/edge_reconfigure_manager.py
topological_navigation/src/topological_navigation/manager2.py
topological_navigation/tests/conf/test.tmap2
topological_navigation/tests/map_manager.test
topological_navigation/tests/map_manager_tester.py
topological_navigation_msgs/msg/UpdateEdgeConfigReq.msg
topological_navigation_msgs/srv/UpdateEdgeConfig.srv
topological_utils/CMakeLists.txt
topological_utils/launch/topological_map_edition.launch
topological_utils/package.xml
topological_utils/scripts/edge_reconf_groups_to_tmap2.py

Copy of PR #183 without Saga CI commits

Update LCAS branch with SAGA branch

---

topological_navigation/package.xml

tf is a run depend, not a test depend.

Removed move base as dependency

---

topological_navigation/CMakeLists.txt
topological_navigation/scripts/navigation.py

Also add checks in nav script to make sure there are closest edges.

Initialise class variable

---

bayesian_topological_localisation/scripts/localisation_node.py
bayesian_topological_localisation/src/bayesian_topological_localisation/particle_filter.py

This makes the bayesian localisation node wait for topomap before announcing their services.

localisation_node waits for topomap before starting services

---

topological_utils/config/goal.yaml
topological_utils/scripts/goal_converter.py

Change the goal of a specific action in all tmaps located under a root directory.
usage is goal_converter.py root_directory action action_type goal
eg.
`rosrun topological_utils goal_converter.py $(rospack find rasberry_core)/config/site_files action package/GoalDefinition $(rospack find topological_utils)/config/goal.yaml`

Goal Converter

---

topological_navigation/scripts/navigation.py
topological_navigation/scripts/visualise_map2.py
topological_utils/scripts/goal_converter.py
topological_utils/scripts/map_converter.py

Apologies conflating two bugfixes into on PR, but it's simple (and late say @gcielniak):
1. the map converter didn't work in noetic
2. some topic names where "root-ed" that shouldn't be in multi-robot (namespace) setups

Some Python3 and multi-robot fixes

---

topological_navigation/package.xml
topological_navigation/setup.py
topological_navigation/topological_navigation/policy_marker.py
topological_navigation/topological_navigation/scripts/topological_transform_publisher.py
topological_navigation/topological_navigation/scripts/visualise_map_ros2.py
topological_navigation/topological_navigation/testing.py
topological_navigation/topological_navigation/topomap_marker.py
topological_navigation/topological_navigation/topomap_marker2.py
topological_navigation_msgs/CMakeLists.txt
topological_navigation_msgs/msg/ExecutePolicyModeGoal.msg

I am leaving this PR here for now as a basis for the next stage of development. In this state, everything is working to facilitate a basic system for map management, visualisation, and routing. However, these facilities are working in an hacky state and need to be formalised eventually.
So far, we have utilised topological navigation as a collection of two systems, a robot-side system for navigation and localisation, and a server-side system for map management, restrictions management and fleet routing. However, this server-side system had never been formally defined, being instead developed for utilisation locally on the robot.
We have previously used the server-side capabilities on the server, communicating routes to the robot via mqtt_bridge considering the execute policy mode action …

Development work toward a working ROS2 version

---

topological_navigation/setup.py
topological_navigation/topological_navigation/manager2.py

Now it can be built using both `colcon build` and `colcon build --symlink-install`

fixing colcon build issue

---

topological_navigation/setup.py
topological_navigation/topological_navigation/scripts/get_simple_policy2.py

To validate:
ros2 service call /get_simple_policy/get_route_between topological_navigation_msgs/srv/GetRouteBetween "{origin: r6.5-ca, goal: r6.5-cz}"
ros2 service call /get_simple_policy/get_route_to topological_navigation_msgs/srv/GetRouteTo "{ goal: r3-cz}"

adding simple policy server

---

topological_navigation/topological_navigation/topomap_marker.py
topological_navigation/topological_navigation/topomap_marker2.py

Commit to include the legend spacing into the tmap rescaling callback

Scaling added to legend

---

topological_navigation/topological_navigation/edge_action_manager2.py
topological_navigation/topological_navigation/scripts/actions_bt.py
topological_navigation/topological_navigation/scripts/navigation2.py

For each selected action type, it is possible to set the corresponding  nav2 control server parameters

adding server config for each action
